version: '3.8'

services:
  frontend:
    image: rafauser/insurance-frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - insurance-network

  backend:
    image: rafauser/insurance-backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=your-super-secret-jwt-key-for-security-testing-2024
      - PORT=3001
      - NODE_ENV=production
      - CORS_ORIGINS=http://localhost,http://localhost:80,http://frontend:80,https://apitestinginsurance.azurewebsites.net
    networks:
      - insurance-network

networks:
  insurance-network:
    driver: bridge
